# managed by hyprdynamicmonitors
monitor=eDP-1,1920x1080@120.00,0x0,1
monitor=HDMI-A-1,1920x1080@72.00,0x-1080,1

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
# monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1

source = ~/.cache/wallust/colors-hyprland.conf
general {
     # Gaps and border
     gaps_in = 1
     gaps_out = 1
     gaps_workspaces = 50
     border_size = 2
     col.active_border = $active_border_color_1 $active_border_color_2 45deg
     col.inactive_border = rgba(22222233)
    
	resize_on_border = true
     no_focus_fallback = true
     layout = dwindle
    
     #focus_to_other_workspaces = true # ahhhh i still haven't properly implemented this
     allow_tearing = true # This just allows the `immediate` window rule to work
}
animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = fastDecel, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 3, fastDecel, popin 85%
    animation = windowsIn, 1, 3, winIn, popin 85%
    animation = windowsOut, 1, 2, winOut, popin 85%
    animation = windowsMove, 1, 3, wind, slide
    animation = fade, 1, 2, default
    animation = layers, 1, 2, fastDecel, popin 85%
    animation = layersIn, 1, 2, fastDecel, popin 85%
    animation = layersOut, 1, 2, fastDecel, popin 85%
    animation = workspaces, 1, 3, wind
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    animation = specialWorkspace, 1, 2, md3_decel, slidevert
}
# decoration {
#     rounding = 10
#     blur {
#         enabled = false
#         size = 5
#         passes = 1
#     }
#     #drop_shadow = true
#     #shadow_range = 4
#     #shadow_render_power = 3
#     #col.shadow = rgba(1a1a1aee)
# }


decoration {
    rounding = 8
    dim_special = 0.5
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    blur {
        special = true
        xray = false
    }
}



# decoration {
#     dim_special = 0.3
#     active_opacity = 0.90
#     inactive_opacity = 0.75
#     fullscreen_opacity = 1
#     blur {
#         special = true
#     }
# }

# windowrule = opacity 0.9 0.75 1.0, class:^(code)$
# windowrule = opacity 0.9 0.75 1.0, class:^(firefox)$

# windowrule = blur, match:class (code)

# windowrule = noblur, match:class ^(mpv|kitty|zen|thorium|brave-browser|Helium|firefox)$
# windowrule = noblur, match:title ^(Picture-in-Picture)$
#
# windowrule = blur, match:negative:class ^(mpv|kitty|zen|thorium|brave-browser|Helium|firefox)$
# windowrule = blur, match:negative:title ^(Picture-in-Picture)$

# layerrule = blur true,match:namespace rofi
# layerrule = ignore_alpha 0,match:namespace rofi
# layerrule = blur true,match:namespace notifications
# layerrule = ignore_alpha 0,match:namespace notifications
# layerrule = blur true,match:namespace swaync-notification-window
# layerrule = ignore_alpha 0,match:namespace swaync-notification-window
# layerrule = blur true,match:namespace swaync-control-center
# layerrule = ignore_alpha 0,match:namespace swaync-control-center
# layerrule = blur true,match:namespace logout_dialog



# disable blur for these apps
# windowrule = no_blur on,match:class ^(mpv|kitty|Brave-browser|Thorium-browser|Zen|Helium|anybrowser)$

windowrule = opacity 0.95,match:class ^(kitty|ghostty)$


