# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
# preload = ~/.config/broconfig/walls/gtrwall4k.jpg
# wallpaper = ,~/.config/broconfig/walls/gtrwall4k.jpg
# Global settings
ipc = on
splash = false

# Laptop Screen
wallpaper {
    monitor = eDP-1
    path = ~/Downloads/wallpaper/heroscreen_cyber.jpg
    fit_mode = cover
}

# External Monitor
wallpaper {
    monitor = HDMI-A-1
    path = ~/Downloads/wallpaper/heroscreen_cyber.jpg
    fit_mode = cover
}
