preload = /home/catisgoal/.config/background.jpg

wallpaper {
    monitor = eDP-1
    path = /home/catisgoal/.config/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/catisgoal/.config/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/catisgoal/.config/background.jpg
    fit_mode = cover
}

splash = false
