# ######## Layer rules ########
layerrule = xray 1, match:namespace .*
# layerrule = noanim, .*
layerrule = no_anim on, match:namespace walker
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace overview
layerrule = no_anim on, match:namespace anyraun
layerrule = no_anim on, match:namespace indicator.*
layerrule = no_anim on, match:namespace osk
layerrule = no_anim on, match:namespace hyprpicker
#layerrule = blur, shell:*
layerrule = ignore_alpha 0.6, match:namespace shell:*

layerrule = no_anim on, match:namespace noanim
# layerrule = blur, gtk-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk-layer-shell
# layerrule = blur, launcher
layerrule = ignore_alpha 0.5, match:namespace launcher
# layerrule = blur, notifications
layerrule = ignore_alpha 0.69, match:namespace notifications

layerrule = animation popin 85%, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.2, match:namespace rofi
